# Generated by Django 5.0.8 on 2024-09-03 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=70)),
                ('Username', models.CharField(max_length=70, unique=True)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('UserPassword', models.CharField(max_length=60)),
                ('UserRole', models.BooleanField(default=False)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('EmailVerified', models.BooleanField(default=False)),
                ('UpdatedDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('IsActive', models.BooleanField(default=False)),
                ('Canlogin', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('ResetID', models.AutoField(primary_key=True, serialize=False)),
                ('ResetToken', models.CharField(max_length=70)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ExpireDate', models.DateTimeField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datascience_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('AttemptID', models.AutoField(primary_key=True, serialize=False)),
                ('AttemptTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('Successful', models.BooleanField()),
                ('IpAddress', models.CharField(max_length=20)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datascience_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('SessionID', models.AutoField(primary_key=True, serialize=False)),
                ('SessionToken', models.CharField(max_length=255, unique=True)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ExpireDate', models.DateTimeField()),
                ('IpAddress', models.CharField(max_length=45)),
                ('UserAgent', models.TextField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datascience_app.user')),
            ],
        ),
    ]
