# Generated by Django 5.0.8 on 2024-09-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascience_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserPassword',
            field=models.CharField(max_length=255),
        ),
    ]
