# Generated by Django 5.0.8 on 2024-09-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascience_app', '0002_alter_user_userpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserPassword',
            field=models.CharField(max_length=60),
        ),
    ]
