# Generated by Django 5.0.8 on 2024-09-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascience_app', '0003_alter_user_email_alter_user_userpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserPassword',
            field=models.CharField(max_length=255),
        ),
    ]
