# Generated by Django 5.0.8 on 2024-09-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascience_app', '0004_alter_user_userpassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
