# Generated by Django 5.0.8 on 2024-09-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascience_app', '0005_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
