# Generated by Django 5.0.8 on 2024-09-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascience_app', '0007_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginattempt',
            table='users.LoginAttempts',
        ),
        migrations.AlterModelTable(
            name='passwordreset',
            table='users.PasswordResets',
        ),
        migrations.AlterModelTable(
            name='usersession',
            table='users.UserSessions',
        ),
    ]
