# Generated by Django 5.0.8 on 2024-09-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascience_app', '0008_alter_loginattempt_table_alter_passwordreset_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='USER',
        ),
    ]
